// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhM2rMlCoB-hexfBrXVS60TihRrx3JGPI',
    appId: '1:616730094469:web:84ec4427dd27d3937c72ec',
    messagingSenderId: '616730094469',
    projectId: 'diwali-sweets-biller',
    authDomain: 'diwali-sweets-biller.firebaseapp.com',
    storageBucket: 'diwali-sweets-biller.firebasestorage.app',
    measurementId: 'G-S8EQ89KNE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ShOPLjaqagZxzG2TGW3xEreFgXFGZlA',
    appId: '1:616730094469:android:2b7c2dd647c68c7c7c72ec',
    messagingSenderId: '616730094469',
    projectId: 'diwali-sweets-biller',
    storageBucket: 'diwali-sweets-biller.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgBhjSJqnONUsR9S7pO2YgKewuttlO80M',
    appId: '1:616730094469:ios:b003658c3c96b8467c72ec',
    messagingSenderId: '616730094469',
    projectId: 'diwali-sweets-biller',
    storageBucket: 'diwali-sweets-biller.firebasestorage.app',
    iosBundleId: 'com.example.diwaliSweetsBiller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgBhjSJqnONUsR9S7pO2YgKewuttlO80M',
    appId: '1:616730094469:ios:b003658c3c96b8467c72ec',
    messagingSenderId: '616730094469',
    projectId: 'diwali-sweets-biller',
    storageBucket: 'diwali-sweets-biller.firebasestorage.app',
    iosBundleId: 'com.example.diwaliSweetsBiller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhM2rMlCoB-hexfBrXVS60TihRrx3JGPI',
    appId: '1:616730094469:web:a3ce578487ff90847c72ec',
    messagingSenderId: '616730094469',
    projectId: 'diwali-sweets-biller',
    authDomain: 'diwali-sweets-biller.firebaseapp.com',
    storageBucket: 'diwali-sweets-biller.firebasestorage.app',
    measurementId: 'G-110DE9ER1B',
  );

}